# docker-compose utilisé pour un déploiement sur serveur
# Pour le poste de developement, utiliser docker-compose.yml à la racine du projet
version: "3.4"
services:
  rece-ui:
    restart: unless-stopped
    container_name: rece-ui
    image: gitlab-registry.forge.diplomatie.gouv.fr/rece/ui/rece-ui/rece-ui-static:${VERSION_IMAGE_APP}
    networks:
      - apache_frontend

networks:
  apache_frontend:
    external:
      name: apache_frontend
  